GPH_DIR=./gph/
PIC_DIR=./pic/
PLT_DIR=./plt/
SCH_DIR=./sch/

.PHONY: gph pic plt sch

all: gph pic plt sch

gph:
	$(MAKE) all -C $(GPH_DIR)

pic:
	# $(MAKE) all -C $(PIC_DIR)

plt:
	# $(MAKE) all -C $(PLT_DIR)

sch:
	$(MAKE) all -C $(SCH_DIR)

